Repository SanchitGeez/Investra, pull requests merged in 2024-10, with the labels that each got.

#87 Added Contributors profile. Fixed issue #56
  README.md
Labels: gssoc-ext, gssoc, level1, hacktoberfest, hacktoberfest-accepted

#41 Added dropdown recommendation and updated its css(Issue #6)
  client/app/Dash/page.js
  client/app/Dash/styles.css
Labels: gssoc-ext, gssoc, level3, hacktoberfest, hacktoberfest-accepted

#45 [UI] Added Signup and Login guiding text to the pop up of login and signup
  client/app/globals.css
  client/app/page.js
Labels: gssoc-ext, gssoc, level1, hacktoberfest, hacktoberfest-accepted

#89 ✨chatbot added✨
  client/app/Dash/page.js
  client/app/Forget-Password/page.js
  client/app/chatBot.jsx
  client/app/page.js
Labels: gssoc-ext, gssoc, level2, hacktoberfest, hacktoberfest-accepted

#91 Create greetings.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, gssoc, level2, hacktoberfest, hacktoberfest-accepted

#65 Login/SignUp/forgot Passord Button Improvement. #47
  .gitignore
  client/app/Dash/page.js
  client/app/Dash/styles.css
  client/app/globals.css
Labels: gssoc-ext, gssoc, level1, hacktoberfest, hacktoberfest-accepted

#63 Fixed Event Bubbling bug on the Sign up Page
  client/app/page.js
Labels: gssoc-ext, gssoc, level1, hacktoberfest, hacktoberfest-accepted

#61 Added Password regex
  client/app/page.js
Labels: gssoc-ext, gssoc, level1, hacktoberfest, hacktoberfest-accepted
